#version 460
#extension GL_EXT_ray_tracing : enable

layout(binding = 0, rgba32f) uniform image2D image;
layout(binding = 1) uniform CameraProperties {
    int frameIndex;
    int _pad0;
    int _pad1;
    int _pad2;
    mat4 viewInverse;
    mat4 projInverse;
} cam;
layout(binding = 2) uniform accelerationStructureEXT topLevelAS;

struct HitInfo
{
    bool isHit;
    vec3 color;
};

layout(location = 0) rayPayloadEXT HitInfo hitInfo;

void main()
{
    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;

    vec4 origin = cam.viewInverse * vec4(0, 0, 0, 1);
    vec4 target = cam.projInverse * vec4(d.x, d.y, 1, 1);
    vec4 direction = cam.viewInverse * vec4(normalize(target.xyz), 0);

    float tmin = 0.001;
    float tmax = 10000.0;

    hitInfo.isHit = false;
    hitInfo.color = vec3(0.0);

    traceRayEXT(topLevelAS, gl_RayFlagsOpaqueEXT, 0xff, 0, 0, 0,
                origin.xyz, tmin, normalize(direction.xyz), tmax, 0);

    vec3 result = hitInfo.color;

    // Progressive accumulation
    vec4 prevColor = vec4(0.0);
    if (cam.frameIndex > 0)
        prevColor = imageLoad(image, ivec2(gl_LaunchIDEXT.xy));
    vec3 finalColor = mix(prevColor.rgb, result, 1.0 / float(cam.frameIndex + 1));
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(finalColor, 1.0));
}
